import { CheckCircle, Search, FileText, DollarSign, ClipboardCheck, Handshake, Scale, Key, Home } from "lucide-react";

export const guideSections = [
  {
    id: "introduction",
    title: "Why Buy Without an Agent?",
    icon: Home,
    content: {
      overview: "Buying a home without a real estate agent? For savvy Millennial homebuyers craving a modern, private, and flexible experience, going solo is not only possible – it's becoming increasingly popular.",
      keyPoints: [
        "Nearly one-third of recent homebuyers (29% in 2024) purchased without an agent",
        "Save thousands vs. the old 6% commission model that can add tens of thousands to costs", 
        "FirstLook offers professional support without pressure or high price tags",
        "Over 1,000 successful home tours facilitated with 12-minute average response time"
      ],
      content: [
        "Many buyers are tired of the old 6% commission model that can add tens of thousands of dollars to a home's cost. By taking control of the process and leveraging new tools like FirstLook, you can save big and stay in the driver's seat.",
        "FirstLook is a DC-based platform built for buyers who want all the perks of professional support without the pressure or price tag of a traditional realtor. It's about empowering you to get your dream home on your terms – and keeping more money in your pocket.",
        "In this guide, we'll walk through the homebuying journey step by step – from planning your budget to moving day – all without a buyer's agent. At each stage, you'll see how FirstLook can support or even replace what a traditional agent would do.",
        "You'll learn how to clarify your needs, search for homes, schedule tours, secure financing, handle inspections, write offers, negotiate like a pro, and close the deal – all while maintaining control and privacy.",
        "Thousands of DC buyers have already discovered this better way to buy, with FirstLook facilitating over 1,000 successful home tours and licensed DC professionals on call to assist when you need them. That means no binding contracts, no pushy sales tactics – just help when you want it, and savings when you close."
      ],
      comparison: {
        aspects: [
          {
            category: "Cost Structure",
            firstlook: "Pay only for what you need – often flat fees or à la carte services. No 3% commission on the buyer side, saving you thousands.",
            traditional: "\"Free\" to the buyer in theory, but seller pays ~3% to your agent (built into price). On a $500,000 home that's ~$15,000 in commission, ultimately costing you via a higher price."
          },
          {
            category: "Home Search",
            firstlook: "Find homes on your own schedule using online tools (Zillow, Redfin, etc.) or FirstLook's platform. You decide what to see – no middleman gatekeeping listings.",
            traditional: "Agent sets up searches (via MLS) and sends you listings they think fit. You rely on their selections and schedule."
          },
          {
            category: "Touring Properties",
            firstlook: "Book home tours instantly on your timeline. FirstLook provides on-demand, licensed local pros to unlock doors and guide you as needed – but only when you request it. Your first tour is free, with no hidden fees.",
            traditional: "Agent must coordinate showings, and you work around their schedule. You're typically tied to one agent by a contract, and their availability can limit when (and how many) homes you see."
          },
          {
            category: "Negotiation & Offers",
            firstlook: "You stay in control. FirstLook offers resources and expert help (like contract templates or on-call negotiators) only when you need it. You can negotiate directly with sellers or their agents, cutting out the \"telephone game\" for faster communication.",
            traditional: "Agent guides your offer strategy, handles contract drafting, and negotiates with the seller's agent on your behalf. Their commission incentive can subtly conflict (a higher sale price means a bigger commission)."
          },
          {
            category: "Flexibility & Control",
            firstlook: "Maximum control. You decide which homes to see and when, which professionals to consult, and how to approach offers. No pressure to rush into a purchase – FirstLook doesn't get a big commission, so their only goal is your satisfaction.",
            traditional: "Guidance-driven. Agents often steer the process – selecting homes, timing tours, suggesting offer terms. You typically sign an exclusive agreement, limiting your flexibility to try different approaches."
          },
          {
            category: "Professional Network",
            firstlook: "FirstLook connects you to vetted third parties when needed: lenders, home inspectors, real estate attorneys, title companies, etc. You get the benefit of an agent's network without committing to full agent services.",
            traditional: "Agents usually provide referrals for lenders, inspectors, attorneys, and so on – which is helpful, but you might feel obliged to use their contacts. In some cases, choices may be limited to their partners."
          }
        ]
      }
    }
  },
  {
    id: "readiness",
    title: "Clarify Your Needs and Finances",
    icon: CheckCircle,
    content: {
      overview: "The first step in any homebuying journey is figuring out what you want and what you can afford. Traditionally, a buyer's agent would ask you a bunch of questions to nail down your wish list and budget. But you absolutely can (and should) do this yourself – after all, you know your situation best!",
      keyPoints: [
        "Define your home requirements with must-haves vs. nice-to-haves",
        "Assess your financial readiness including down payment and closing costs",
        "Research mortgage options and local assistance programs",
        "Create a focused strategy to avoid wasting time on unsuitable properties"
      ],
      content: [
        "Define Your Home Requirements: Make a list of your must-haves and nice-to-haves. How many bedrooms and bathrooms? Do you need a home office or parking spot? Are you set on a specific neighborhood or school district? Get specific about your priorities. This will focus your search so you don't waste time touring homes that aren't a fit. It may help to rank your priorities in order (for example: location, then price, then size, etc.). Remember, without an agent filtering listings for you, it's extra important to have a clear vision of what you're looking for.",
        "Assess Your Financial Readiness: Take a hard look at your finances to understand what price range is realistic. This means reviewing your savings, income, debts, and credit score. In general, you'll want money saved for a down payment (anywhere from ~3% for some first-time buyer programs up to 20% to avoid mortgage insurance) plus about 2–5% of the home price for closing costs and reserves. Use an online home affordability calculator to ballpark what price range and monthly payment you can comfortably handle.",
        "Check Your Mortgage Options: Start researching mortgage rates and loan programs. This isn't about getting a loan just yet – it's about educating yourself on what's available. Look into different loan types (conventional, FHA, VA, etc.), current interest rates, and any first-time homebuyer assistance programs in your area. For example, DC has programs like DC Open Doors and HPAP that can help with down payments if you qualify. Knowing the basics will empower you when it's time to talk to lenders for real.",
        "By clarifying your needs and financial parameters upfront, you set the foundation for a focused, efficient home search. You're essentially acting as your own agent in this stage – defining the criteria that an agent would normally gather from you. Keep your notes handy (consider a simple spreadsheet or note-taking app) and update them as your thinking evolves.",
        "How FirstLook Helps: FirstLook provides tools and templates to help you self-assess your needs. For instance, the platform might prompt you to create a profile with your desired neighborhoods, price range, and home features. This way, when you start searching, FirstLook (or any home search site) can alert you to matching properties. While a traditional agent might quiz you in person, FirstLook lets you thoughtfully consider your priorities on your own, then refine them as you learn more. And when it comes to finances, FirstLook can refer you to trusted mortgage advisors who understand the needs of independent buyers."
      ]
    }
  },
  {
    id: "searching",
    title: "Searching for Homes (Without an Agent)",
    icon: Search,
    content: {
      overview: "House-hunting is the fun part! In the old days, agents had exclusive access to the best home listings through the MLS (Multiple Listing Service). Today, however, the internet has leveled the playing field – almost all listings are available online to consumers in real time.",
      keyPoints: [
        "Leverage online platforms like Zillow, Redfin, and Realtor.com with automated alerts",
        "Use FirstLook's curated search tools tied to local MLS data",
        "Explore neighborhoods in person and virtually to become your own expert",
        "Keep organized comparison sheets and track your favorite properties"
      ],
      content: [
        "Leverage Online Listing Platforms: Start with popular sites and apps like Zillow, Redfin, Trulia, or Realtor.com to browse homes in your target area. You can filter by price, size, location, features, etc. and even set up email alerts for new listings that meet your criteria. Many Millennial buyers actually find the home they end up purchasing through their own online searches, not their agent. Create a dedicated email for home search inquiries – it keeps your main inbox uncluttered and ensures you don't miss alerts. Keep an eye out for new listings daily; in a hot market, good homes can go under contract fast.",
        "Use FirstLook's Home Search Tools: If you're in DC, FirstLook's platform may offer a curated search experience tied into the local MLS data. FirstLook can aggregate listings and provide additional context, like neighborhood stats or commute times, to help you evaluate options. At the very least, FirstLook will allow you to save favorite properties and seamlessly request a tour with one click. Essentially, it combines the browsing power of the big sites with the convenience of an on-demand tour scheduler.",
        "Explore Neighborhoods in Person (and Virtually): Without an agent chauffeuring you to showings, you'll want to become your own neighborhood expert. Drive or walk through areas you're interested in – this gives you a feel for the community that photos can't. Note things like nearby shops, traffic levels, and general upkeep of the area. You can also use Google Street View to virtually \"walk\" the neighborhood. Some buyers even reach out on local forums or social media (e.g. neighborhood Facebook groups or Nextdoor) to ask residents about the area. Remember, an agent often can't tell you subjective things like \"Is this a family-friendly block?\" due to fair housing laws, but as an independent buyer you can do that legwork yourself.",
        "Keep a Comparison Sheet: It's easy to get listing overload when you're searching solo. Consider keeping a simple spreadsheet or notebook to track the homes you like. List addresses, key pros/cons, and questions that arise (e.g., \"House on 14th St – great kitchen, but what's the parking situation?\"). This helps you stay organized. An agent would normally help remind you of a property's details, but your notes can do the same. FirstLook might also keep a history of homes you've viewed or toured on your account, which is handy for reference.",
        "One thing to be aware of: off-market listings and coming soons. Traditional agents sometimes know about homes not yet publicly listed. While you might miss a few of those by not having an agent's insider scoop, many \"coming soon\" homes still find their way to Zillow or local real estate Facebook groups. If you're worried about missing out, you can network a bit – attend open houses (talk to the listing agents), join local real estate meetup groups, or have FirstLook notify you of any exclusive listings they know about. But realistically, the vast majority of buyers find their home through public listings.",
        "How FirstLook Supports Your Search: FirstLook is all about a transparent home search. The platform doesn't push certain listings on you to meet a quota or commission target. Instead, you can use it to bookmark homes you love and get honest, data-driven insights. For example, FirstLook might show you how long a property has been on the market or if there were recent price drops. Also, FirstLook can flag which homes might offer better deals if there's no buyer's agent commission involved. Some sellers may be open to discounting the price if you come without an agent, since it saves them paying the buyer's agent – FirstLook can help identify those opportunities."
      ]
    }
  },
  {
    id: "touring",
    title: "Touring Homes",
    icon: Key,
    content: {
      overview: "Seeing homes in person is where the process really gets exciting – and it's an area where FirstLook truly shines. Traditionally, a buyer's agent schedules tours, holds your hand through each house, and offers opinions. Without an agent, you'll be arranging visits yourself, but that doesn't mean you have to go it completely alone.",
      keyPoints: [
        "Schedule tours directly with listing agents or use FirstLook's instant booking",
        "Attend open houses for low-pressure exploration without appointments",
        "Maintain proper touring etiquette and safety practices",
        "Enjoy privacy and freedom to discuss openly without agent pressure"
      ],
      content: [
        "Scheduling Tours Directly: If you find a house you want to see, you have a couple of options. One is to contact the listing agent or seller directly (if it's a For-Sale-By-Owner) to request a showing. Listing agents' info is usually on the listing page. Let them know you're a serious buyer not working with a buyer's agent. They'll typically be happy to set up a time (after all, you potentially save them from having to pay out half the commission). The other option – and a super convenient one – is to use FirstLook's instant tour booking. FirstLook allows you to pick a date and time online for a home viewing, and they dispatch one of their licensed DC pros to meet you there and facilitate the tour. It's like scheduling an Uber, but for house tours!",
        "FirstLook offers a modern, on-demand touring experience: no binding contracts, same-day scheduling, and licensed local professionals to assist – giving you the freedom to see homes on your terms. This means you don't have to play phone tag with a listing agent or worry about saying the wrong thing – FirstLook handles the coordination for you.",
        "Attending Open Houses: Don't forget the classic open house. These are typically held on weekends for listed properties. You can walk in without any appointment. Just sign in and feel free to explore. If an agent asks you if you're represented, simply say you're browsing on your own (or you can mention you're working with FirstLook – they'll understand that as you being an independent buyer). Open houses are a great, low-pressure way to see multiple homes in a day. Bring a friend along if you want a second opinion or just moral support. One perk of not having your own agent at an open house is you can blend in and listen to other buyers' reactions and questions, which can be insightful.",
        "Touring Etiquette and Safety: When touring without an agent, you're essentially your own agent in the field. Be respectful of the properties – arrive on time, take off shoes if asked, don't go snooping in off-limits areas like locked closets or drawers. Feel free to take photos or videos (with permission if the owner is present) so you can review them later. It's a good idea to prepare a checklist for each tour: note your impressions of the layout, condition, neighborhood vibe, etc., and jot down any questions. Always keep safety in mind too: it's rare, but if you're meeting a stranger for a FSBO showing, let someone know where you'll be. With FirstLook, you'll have a vetted professional with you, adding a layer of comfort and security.",
        "Privacy and Freedom: One thing many FirstLook users love is the privacy and freedom of touring without feeling like someone is trying to \"sell\" them. You can discuss openly with your partner or friend on the tour about what you like or don't like, without worrying about swaying an agent's strategy. Some buyers feel more at ease examining the nitty-gritty (like opening cabinets, testing the water pressure) when they're not being closely watched by their own agent. The key is, it's your choice. FirstLook's role is simply to grant you access and answer questions – no hard sales pitch.",
        "How FirstLook Makes Touring Easy: This is one of FirstLook's hallmark features – instant tour bookings and on-demand agents. Unlike a traditional agent who might say \"I'm only free on Friday at 3 PM to show you houses,\" FirstLook has a network of local agents ready to go when you are. Want to see a new listing today at lunch? Just hop on the app/website, select a time, and chances are you'll get a confirmed tour often within minutes. The first tour is free, and thereafter you pay a modest flat fee per tour (which is often credited back to you if you end up purchasing with FirstLook's help). This approach means you can tour more homes, more conveniently – a huge plus in competitive markets where timing is everything."
      ]
    }
  },
  {
    id: "financing",
    title: "Securing Financing",
    icon: DollarSign,
    content: {
      overview: "Financing is a crucial piece of the puzzle – and one where you'll want your ducks in a row early. Traditionally, a realtor would often insist you get pre-approved for a mortgage before they start showing you too many houses. This is wise advice, and it applies whether or not you have an agent. In a competitive market, having a mortgage pre-approval letter ready to go is almost mandatory when making an offer.",
      keyPoints: [
        "Shop around with multiple lenders to find the best rates and terms",
        "Get pre-approved before making offers to show sellers you're serious",
        "Understand different loan programs that fit your situation",
        "Stay within your comfort zone, not just your maximum approval amount"
      ],
      content: [
        "Shop for a Mortgage Lender: Start by researching and comparing a few lenders – these can be banks, credit unions, or online mortgage companies. You want a lender that offers competitive rates and good service (responsiveness is key when you're trying to close a deal fast). You can begin with your own bank to see what they offer, but don't stop there. Use online rate comparison tools or reach out to lenders that frequently work with first-time buyers. Many buyers without agents still manage to get quotes from multiple lenders – a smart move that could save you thousands in interest. Remember, you are not obligated to go with the first lender who pre-approves you; you're shopping around for the best deal.",
        "Get Pre-Approved: A pre-approval means a lender has checked your credit, income, and basic finances and is willing to lend you up to a certain amount (pending the home appraisal and other verification later). This comes in the form of a letter. To get one, you'll need to submit an application (often you can do this online in 15-20 minutes) and provide documents like pay stubs, W-2s, bank statements, etc. Within a day or two (sometimes even a few hours), the lender can issue a pre-approval letter stating you are pre-approved for up to $X amount. Get the pre-approval before you start making offers – sellers and their agents will take you far more seriously if you can say \"I'm pre-approved for my financing\" right off the bat. And don't worry, getting pre-approved doesn't lock you into that lender or loan; you can still negotiate or switch lenders later if needed.",
        "Know Your Loan Programs: When talking to lenders, inquire about what loan programs fit your situation. For example, if you have excellent credit and a 20% down payment, a conventional loan is likely best. If you have a smaller down payment, maybe an FHA loan could work (common for first-time buyers, requiring as little as 3.5% down). If you're a veteran or active military, VA loans offer zero down. DC and many states also have first-time buyer programs that a knowledgeable lender can help you access (like down payment assistance or special interest rates). Without an agent's guidance, you'll rely on the lender to walk you through these options – don't hesitate to ask questions. Good lenders are used to working directly with buyers and will happily explain the pros/cons of each loan type.",
        "Consider Your Budget vs. Approval: Just because you get pre-approved for, say, $600,000 doesn't mean you should spend that much. Revisit your own budget (from Step 1) and make sure the monthly payment at that price won't cramp your lifestyle. It's easy to get carried away when a bank green-lights a high amount, but you don't want to be \"house poor.\" One advantage of flying solo: there's no agent trying to push you to your max just to increase their commission. Stick to what you are comfortable with. You can tell your lender a lower number to put on the pre-approval letter if you prefer your offers to be for less (e.g., you might be approved up to $600k, but looking to buy around $500k – you can request the letter say $500k to not tip your hand on higher affordability).",
        "Prepare for Earnest Money and Down Payment: Part of financing prep is ensuring you have liquid funds ready for the earnest money deposit and down payment. When you make an offer, you'll typically need 1-3% of the price as a good-faith deposit (which later counts toward your down payment). Make sure that money is accessible (in a checking account, not tied up in long-term investments that take time to withdraw). Also avoid making any big changes that could upset your finances: don't open new credit lines, don't make large unexplained deposits, and don't switch jobs right before or during the home purchase process. Lenders will re-verify your info before closing, and any of those could jeopardize your loan approval.",
        "FirstLook's Role in Financing: While FirstLook isn't a lender, they do provide guidance to keep you on track. The platform will remind you to get pre-approved early, and can even connect you with partner lenders who are familiar with assisting buyers without traditional agents. These lenders know you might need a bit more direct communication (since there's no agent acting as a go-between) and they're prepared to give you that concierge service. FirstLook might also offer tools like a mortgage calculator or a checklist of documents you'll need for pre-approval, streamlining the process for you. In essence, FirstLook ensures that when you find \"the one\" – that perfect house – you're financially ready to pounce, with financing in place and no delays."
      ]
    }
  },
  {
    id: "due-diligence",
    title: "Due Diligence and Inspections",
    icon: ClipboardCheck,
    content: {
      overview: "Once you have an accepted offer, the real work begins behind the scenes. This phase – often called due diligence or the inspection period – is where you ensure the home is in good condition and that you're fully comfortable with proceeding. Normally, a buyer's agent would help coordinate inspections, negotiate repairs, and keep track of deadlines. Without an agent, you'll need to be proactive in these areas, but it's entirely manageable with a bit of organization.",
      keyPoints: [
        "Hire a licensed home inspector and attend the inspection",
        "Review all seller disclosures and HOA documents carefully",
        "Understand appraisal process and other contingencies",
        "Track all deadlines to protect your contingency rights"
      ],
      content: [
        "Hire a Home Inspector: A thorough home inspection is a must, especially if you're buying without an agent's experienced eye on the property. As soon as your offer is accepted (often you'll have a set number of days in the contract to complete inspections – commonly 5-10 business days), hire a licensed home inspector to go through the house top to bottom. You can find a reputable inspector by reading online reviews, asking friends for recommendations, or using FirstLook's network of vetted inspectors. The cost is typically around $300-$600 depending on the size of the home – worth every penny for peace of mind. Plan to attend the inspection if you can. It's like a crash course in your future home: the inspector will point out issues (big and small), maintenance tips, and more. Take notes and ask questions. If the inspector flags any major issues (e.g., roof leaks, old electrical wiring, foundation cracks), you may need to get a specialist to evaluate or give estimates.",
        "Review Seller Disclosures and Documents: In parallel with the inspection, you should receive any disclosure documents from the seller. These can include things like a disclosure of known problems, past repairs, termite reports, or if it's a condo/HOA, a package of HOA documents and bylaws. Read these carefully! Without an agent to summarize them, you'll need to digest the info yourself. Look for red flags like mention of previous flooding, foundation repairs, or big upcoming HOA fee increases. If something is confusing (easy to happen, especially with HOA documents), consider consulting an attorney for clarity or asking the seller's agent directly for explanation. FirstLook can assist by highlighting key sections of these documents or suggesting questions to ask. Don't be shy about requesting clarification – you have a right to know what you're buying.",
        "Appraisal and Other Contingencies: If you're using a mortgage, the lender will schedule an appraisal to verify the home's value. This isn't something you do; it happens in the background. But you should know it's happening. Occasionally, the appraisal might come in lower than your purchase price – at which point you'd have to negotiate with the seller or bring extra cash. Many contracts have an appraisal contingency, allowing you to back out or renegotiate if that occurs. If you waived it, then you'd have to cover any shortfall. Since you likely don't have an agent advising you on such contingencies, hopefully you included an appraisal contingency (or at least knew the risk). Apart from appraisal, think of any other checks you want: for example, a radon test (common in some areas), a sewer line scope, or checking for lead paint in older homes. You can hire specialists for these if your general inspector doesn't cover them. It's up to you to decide what's needed based on the home's age and condition.",
        "Negotiate Repairs or Credits (if needed): Once inspections are done, you might find some issues that you feel the seller should address. Common examples: a leaking water heater, a termite infestation, or an HVAC system at end-of-life. Without a buyer's agent, you will directly communicate with the seller (or usually the seller's agent) to request repairs or a price reduction/credit. Keep your requests reasonable and focused on the big-ticket safety or functionality items – not cosmetic issues. For instance, asking to fix a structural problem is fair; asking for a $200 paint credit for scuffed walls might not go over well. Write up a clear list of what you want and why. FirstLook can provide a template for a repair request addendum and even advise on what's customary to ask for. Remember, the seller's agent knows you're unrepresented and might try to influence you, but remain firm on items that truly matter. If negotiating repairs feels daunting, this could be a good time to consult a real estate attorney or hire an on-demand agent for a flat fee to help craft the request – you'll still save money versus a full commission, and you'll have backup.",
        "Track Your Deadlines: In a typical contract, there are deadlines for inspection, appraisal, financing approval, etc. Without an agent's transaction coordinator reminding you, it's your responsibility to calendar these. If your inspection contingency expires on, say, the 10th day and you haven't formally requested repairs or given notice to cancel, you could lose that leverage. So mark the dates and act in advance. It helps to have all your key dates in one place (use your phone calendar with alerts, for example).",
        "FirstLook's Guidance During Due Diligence: FirstLook won't leave you hanging once you're under contract. The platform or your assigned support rep (if you opt for offer/closing assistance) will send you reminders of critical deadlines – \"Inspection contingency expires in 3 days, have you completed inspections?\" – that sort of nudge can be invaluable. They also maintain a roster of qualified home inspectors and specialists. Many FirstLook users tap into this network, essentially replacing the agent's referral role. Moreover, FirstLook can connect you with a real estate attorney at this stage if you don't already have one. Attorneys can be especially helpful in reviewing legal documents or drafting repair requests. In DC, having an attorney isn't required to buy a home, but it can be comforting to know you have a legal expert to call if anything gets complicated. FirstLook's goal here is to ensure you don't miss anything that a professional pair of eyes would catch – helping you be thorough and protected, without paying a percentage-of-sale commission for the privilege."
      ]
    }
  },
  {
    id: "making-offers",
    title: "Making Offers and Negotiating",
    icon: FileText,
    content: {
      overview: "Here's the big moment – you've found the house and are ready to make an offer. Writing an offer and negotiating the price/terms is one of the most critical parts of a real estate deal. It's also the phase where not having an agent can feel most intimidating to many buyers. But take heart: with preparation, and possibly some targeted professional help, you can absolutely do this.",
      keyPoints: [
        "Research comparable sales to determine fair value",
        "Highlight the commission savings in your offer",
        "Use professional offer templates or services",
        "Stay flexible but know your limits"
      ],
      content: [
        "Crafting Your Offer (Offer Writing 101): A real estate offer in DC (and generally) is a legal contract, often called a Purchase and Sale Agreement or Contract of Sale. If you were working with an agent, they'd fill in a standard form for you. Going solo, you have a few ways to get the contract drawn up: you can obtain a standard contract form for your area (some state Realtor associations sell them online or you might find templates), work with a real estate attorney to draft one, or even ask the seller's agent to write the offer and send it to you to sign (though be cautious – the seller's agent represents the seller's interests, so have a lawyer review anything they draft on your behalf). Many solo buyers choose to hire an attorney at this stage for a flat fee to ensure the paperwork is done right. In fact, some attorneys specialize in \"transactional assistance\" for buyers without agents, charging a reasonable fee (often a few thousand dollars or less) to handle the contract and negotiation details – a fraction of the typical agent commission.",
        "Purchase Price: The amount you're offering for the home. This is obviously the headline term. Deciding on this number requires looking at recent comparable sales (comps) and the home's condition. Without an agent's CMA (comparative market analysis), you can research comps on Zillow or Redfin (they often show last sold prices of nearby homes) or ask your FirstLook tour agent for their opinion. Also consider how long the home has been on the market – if it's brand new to market in a hot area, you may need to offer at or above asking to be competitive. If it's been sitting for a while or needs work, you might go under asking. FirstLook can provide guidance here by supplying market data or even a suggested offer range if you ask. Remember, you might also factor in the commission savings: since you have no buyer's agent, in some cases you could justify an offer a bit lower because the seller isn't paying a buyer-agent commission. For example, one strategy is to offer ~3% below the list price, noting that it saves the seller the same amount in commissions – this way both you and the seller benefit from the cut of the middleman. (E.g., on a $250,000 listing, offering $242,500 could net the seller roughly the same as $250k would have with a buyer agent commission – a win-win.) Just be sure to communicate that rationale in a cover letter or email so the seller understands your logic.",
        "Earnest Money Deposit (EMD): The amount of a good-faith deposit you'll put down once the offer is accepted. Commonly 1–3% of the purchase price. This money goes into an escrow account (usually held by the title company) and later counts toward your down payment. If you walk away without a valid contingency reason, the seller may keep this, but if the deal closes it's yours. A larger EMD can signal a strong offer, but only put up what you're comfortable potentially forfeiting (in worst case). You'll typically need to write a check or send a wire within a few days of acceptance.",
        "Financing and Inspection Contingencies: These clauses give you windows to secure your mortgage approval and inspect the home. A financing contingency allows you to exit if you fail to get approved, while an inspection contingency lets you request repairs or cancel if serious issues are found. Many buyers keep these contingencies, though in ultra-competitive situations some waive them (risky unless you're very sure). Without an agent, lean conservative – these are your safety nets. You can also state an inspection as \"inspection with right to terminate\" – basically, you won't ask for repairs but reserve the right to walk away if the inspection is unsatisfactory.",
        "Closing Date and Other Terms: Propose a date for settlement (closing). Typically 30 to 45 days from contract acceptance for financed purchases. Try to be flexible to the seller's needs here – if they want a quick close or need more time, accommodating that can make your offer more attractive. FirstLook can find out from the listing agent if there's a preferred closing timeframe. You can also offer a rent-back if the seller needs to stay in the home for a short period after closing. Keep your offer as clean and simple as possible. Too many demands can turn off a seller. Focus on the key deal points – price, contingencies, timing – and don't clutter with minor asks.",
        "Negotiation Strategies: Once you submit your offer, the seller can accept, reject, or counter-offer. Without a buyer's agent, you'll be dealing directly with the seller or their agent. Leverage your position as an unrepresented buyer by highlighting the commission savings – both parties can benefit when there's no buyer's agent commission. Keep communication professional and prompt; since you don't have to play telephone tag through two agents, you can respond quickly. Focus on win-win solutions rather than fault-finding, and avoid disparaging the home as a negotiation tactic. Have a limit and plan B ready, and don't hesitate to bring in professional help for negotiation advice if needed.",
        "FirstLook can provide standard contract forms or templates for DC area transactions. In many cases, FirstLook has an arrangement where a licensed agent (affiliated with their service) or an attorney will help draft the offer paperwork for you when you're ready, ensuring everything is filled out correctly and legally compliant. This might come as a one-time flat fee or as part of a premium package, but remember – even paying a few hundred dollars for professional offer drafting is a far cry from paying a 3% commission on the whole home price. During negotiations, FirstLook acts as your on-demand transaction coordinator, helping you understand counter-offers, providing market data, and connecting you with experts when needed."
      ]
    }
  },
  {
    id: "closing",
    title: "Legal Support and Closing",
    icon: Scale,
    content: {
      overview: "You've gone under contract – congratulations! Now it's time to cross the finish line, legally transferring the property to you. Closing is the final stage of the homebuying process, and it involves a lot of paperwork, coordination with a title company or attorney, and handling of money. In a traditional scenario, a buyer's agent would shepherd you through this, making sure all the pieces come together by closing day. Doing it without an agent means you'll need to be on top of the process, but don't worry: the heavy lifting is often done by the title company (or closing attorney) and your lender.",
      keyPoints: [
        "Choose an experienced title company or closing attorney",
        "Stay in close contact with your lender throughout the process",
        "Complete your final walk-through before closing",
        "Review all closing documents carefully on signing day"
      ],
      content: [
        "Choose a Title Company or Closing Attorney: In DC and many states, closings are handled by a title company (which provides title insurance and escrow services) or sometimes an attorney's office. Often, the buyer has the right to select the title company. If you have no preference, the seller's side might recommend one. But since you're unrepresented, it's smart to pick a company known for working well with FSBO (for-sale-by-owner) or unagented deals. You want a proactive title agent who will keep everyone (you, seller, lender) on track. If you're unsure, FirstLook can recommend a trusted title company that they frequently work with. A good title company will conduct a title search (to ensure no liens or ownership disputes on the property), issue a title insurance policy to protect you, draft the closing documents, and handle all funds in escrow. They are a neutral party – they don't represent buyer or seller, so you can lean on them for procedural guidance without worry. Also, title services' fees are usually fixed or regulated, and you can ask for a quote upfront.",
        "Work Closely with Your Lender: Now is the time to stay in close contact with your mortgage lender. They will generate a lot of paperwork (loan estimate, then a formal loan commitment, and finally closing disclosures). Be responsive to any requests – they might ask for updated pay stubs, further explanations on a bank deposit, etc. Without an agent, you'll act as the liaison between lender and other parties for some things. For instance, the lender will need the signed contract (you or FirstLook should send it to them immediately upon ratification). They'll also coordinate an appraisal and eventually send loan documents to the title company for closing. If any issues come up, such as the appraisal being late or underwriting needing more info, jump on those quickly. You want your financing fully approved before closing day. Most lenders provide a closing disclosure (CD) at least 3 days before closing – review it carefully. It outlines all the costs, your final loan terms, and how much money you need to bring to closing.",
        "Final Walk-Through: Usually the day before or morning of closing, buyers do a final walk-through of the property to ensure it's in the same condition (or as agreed) and any negotiated repairs were completed. You'll coordinate this directly with the seller or their agent. It's often quick, 30 minutes or so, just checking that there's no new damage and that the place is empty (aside from any items that convey). If you find something egregious – like the seller removed appliances that were supposed to stay, or a new leak has sprung – you need to bring it up before closing. You could delay closing or require money held in escrow until it's resolved. In most cases, final walk-through is smooth. Bring along your contract to verify what stays (appliances, fixtures, etc.). If you used FirstLook for tours, you might ask if a FirstLook agent can accompany you on the walk-through for a second pair of eyes – they might do that as a courtesy or small fee.",
        "Close the Deal – Signing Day: Closing day will typically take place at the title company's office or a mutually agreed location. You (and anyone else on the loan/title, like a spouse) will need to bring a government ID and either a cashier's check or proof of wire transfer for the amount you owe (down payment + closing costs minus any deposit already paid). The title company will have a big stack of documents for you to sign – mortgage note, deed of trust, affidavits, title insurance forms, tax forms, etc. Without an agent present, you might feel a bit alone at that table, but know that it's routine. The title officer or attorney will walk you through each document's purpose. Take your time and read anything if you want; don't be afraid to ask \"what is this one for?\" – they'll explain. One thing you don't have to worry about is the seller trying any shenanigans at closing; by this point everything is agreed in writing, so it's mostly a formality of executing documents.",
        "Exchange of Keys and Celebration: After all papers are signed and money is transferred, you'll get the keys to your new home! If the seller is there (often sellers pre-sign ahead of time and might not be present), you might do a quick key handoff and friendly wave. Sometimes the seller's agent will hand you the keys – even though they weren't your agent, they often attend to wrap up their side. It can feel a bit odd not having a dedicated person to high-five at that moment, but trust me, your sense of accomplishment will fill that void. You did it largely on your own, and that's huge. Now the home is officially yours.",
        "Post-Closing Items: After closing, there are a few loose ends to tie. The title company will record the deed with the jurisdiction (you don't need to do anything). You should get copies of all the signed documents – usually a big packet or PDF. Keep those in a safe place; they include your deed and mortgage agreement. If you negotiated any home warranty or seller-paid item that extends post-closing, make sure to follow up on those. Also, ensure utilities are transferred to your name around the closing date, and change your address at the post office. If you didn't do it yet, update your insurance to homeowner's insurance effective on closing day (your lender likely required proof of insurance for closing anyway). And of course, plan your move!",
        "FirstLook's Closing Support: During the closing phase, FirstLook continues to act as your virtual guide. They'll coordinate with the title company to make sure everything is on track. For example, FirstLook might help by sending the title company all the contact info and documents as soon as you're under contract – essentially acting as a transaction coordinator. They can also schedule your closing appointment for you if needed. If any issues arise (like a title hiccup or a last-minute question about the settlement statement), FirstLook is just a call or text away to assist or explain. They can liaise with the seller or listing agent to smooth out any wrinkles. Basically, FirstLook remains your behind-the-scenes advocate up through closing. And beyond that, many FirstLook users note that the team follows up after closing to ensure you're settling in okay and to answer any new homeowner questions. By not paying a standard buyer's agent commission, you potentially saved thousands. That might mean extra cash for furniture, renovations, or just a bigger cushion in your bank account. Well done!"
      ]
    }
  },
  {
    id: "moving-in",
    title: "Moving In and Next Steps",
    icon: Home,
    content: {
      overview: "Time to enjoy the fruits of your labor – you're a homeowner now, and moving day is here! While moving in might seem straightforward compared to the homebuying gauntlet you just went through, there are still some tips to ensure a smooth transition. And as you settle in, it's worth reflecting on how FirstLook has helped you reach this point and what lies ahead as a confident, commission-savvy homeowner.",
      keyPoints: [
        "Plan your move well in advance with proper organization",
        "Use your commission savings wisely for improvements or savings",
        "Handle post-closing items promptly and stay organized",
        "Enjoy your achievement and new home ownership journey"
      ],
      content: [
        "Plan Your Move Early: As soon as you know your closing date, start organizing the move. Book movers or a truck, start packing gradually, and line up any help you might need. Without an agent, you may not have gotten a glossy \"new home\" packet with checklists – but plenty of moving checklists exist online. Key tasks include: transferring utilities (electric, water, gas, internet) to your name effective your closing day, scheduling any immediate work you want done in the new home (painting, deep cleaning) before you bring all your stuff in, and updating your address for banks, employer, subscriptions, etc. If you're renting your current place, schedule the end of lease and any cleaning to get your deposit back. FirstLook might provide a handy moving day checklist as part of their service, covering often-forgotten items like updating your voter registration and driver's license address.",
        "Use Your Savings to Your Advantage: One amazing thing about buying without a traditional agent is the money you've saved. Earlier, we talked about possibly saving around 3% of the purchase price by avoiding a buyer agent commission. On a $500,000 home, that could be roughly $15,000 (minus any flat fees you paid to FirstLook or attorneys, which are relatively small). Think about that – $15k could cover a lot of improvements or several months of mortgage payments. Consider earmarking some of those savings towards making your new house a home. Maybe you'll build that home theater, invest in energy-efficient appliances, or simply bolster your emergency fund (always a wise move as a new homeowner). The point is, you get to decide, rather than having it invisibly disappear as an agent commission. It's a tangible reward for taking the initiative to go solo.",
        "Tie Up Any Loose Ends: After moving in, there might be a few lingering items from the transaction. Perhaps the seller agreed to mail you an extra set of keys or you're waiting on a contractor's invoice that was a condition of closing. Stay on top of these until they're resolved. If you discover an issue in the house that was supposed to be fixed and wasn't, you can sometimes address it even post-closing if it was explicitly agreed upon. Check your contract and don't hesitate to reach out to the seller (politely) if needed. Without agents, communication is direct, which can actually resolve things faster in some cases. If something serious emerges that wasn't disclosed, consult your attorney – but hopefully, with thorough due diligence, there are no surprises.",
        "Enjoy Homeownership (and Know You Did It Differently): Now comes the fun part – making the place your own! Paint those walls, plant that garden, throw that housewarming party (you earned it). Homeownership is a journey, and you'll keep learning as you go – maintenance tips, how to deal with property taxes, maybe joining the neighborhood association. One thing you've proven by buying without a realtor is that you're a proactive, informed consumer. That will serve you well going forward. You won't hesitate to seek out information and make decisions confidently about your home. And if/when the time comes to sell or buy again, you'll be in a great position to weigh your options – you might even use FirstLook (or similar) on the sell side, or negotiate even harder knowing what you know now.",
        "Stay Connected with FirstLook: Just because the transaction is over doesn't mean your relationship with FirstLook has to end. Many users stay in touch – whether it's getting recommendations for reliable contractors or even using FirstLook's resources for homeowner education (some platforms offer workshops on home maintenance or refinancing tips, for example). And of course, if you have friends or family looking to buy a home in a modern way, you can share your experience. There's often referral benefits too – another bonus of being part of the FirstLook community.",
        "Finally, take a moment to pat yourself on the back. You navigated the entire homebuying process without a traditional realtor, avoiding the limitations and costs of the old model. You proved that with the right approach and support, buyers have more power and savvy than ever. The real estate industry is changing: flat-fee and à la carte services are rising, and consumers are pushing back on high commissions. You're at the forefront of that change. We hope this step-by-step guide has been clear, empowering, and useful in showing that buying a home without an agent is not only feasible – it can be downright liberating. Welcome to your new home, purchased your way. Here's to a future where homebuyers like you have FirstLooked their way to success – enjoying the home they want, the control they need, and the savings they deserve. Cheers!"
      ]
    }
  }
];
