
import { Scale } from "lucide-react";

export const closingSection = {
  id: "closing",
  title: "Legal Support and Closing",
  icon: Scale,
  content: {
    overview: "You've gone under contract – congratulations! Now it's time to cross the finish line, legally transferring the property to you. Closing is the final stage of the homebuying process, and it involves a lot of paperwork, coordination with a title company or attorney, and handling of money. In a traditional scenario, a buyer's agent would shepherd you through this, making sure all the pieces come together by closing day. Doing it without an agent means you'll need to be on top of the process, but don't worry: the heavy lifting is often done by the title company (or closing attorney) and your lender.",
    keyPoints: [
      "Choose an experienced title company or closing attorney",
      "Stay in close contact with your lender throughout the process",
      "Complete your final walk-through before closing",
      "Review all closing documents carefully on signing day"
    ],
    content: [
      "Choose a Title Company or Closing Attorney: In DC and many states, closings are handled by a title company (which provides title insurance and escrow services) or sometimes an attorney's office. Often, the buyer has the right to select the title company. If you have no preference, the seller's side might recommend one. But since you're unrepresented, it's smart to pick a company known for working well with FSBO (for-sale-by-owner) or unagented deals. You want a proactive title agent who will keep everyone (you, seller, lender) on track. If you're unsure, FirstLook can recommend a trusted title company that they frequently work with. A good title company will conduct a title search (to ensure no liens or ownership disputes on the property), issue a title insurance policy to protect you, draft the closing documents, and handle all funds in escrow. They are a neutral party – they don't represent buyer or seller, so you can lean on them for procedural guidance without worry. Also, title services' fees are usually fixed or regulated, and you can ask for a quote upfront.",
      "Work Closely with Your Lender: Now is the time to stay in close contact with your mortgage lender. They will generate a lot of paperwork (loan estimate, then a formal loan commitment, and finally closing disclosures). Be responsive to any requests – they might ask for updated pay stubs, further explanations on a bank deposit, etc. Without an agent, you'll act as the liaison between lender and other parties for some things. For instance, the lender will need the signed contract (you or FirstLook should send it to them immediately upon ratification). They'll also coordinate an appraisal and eventually send loan documents to the title company for closing. If any issues come up, such as the appraisal being late or underwriting needing more info, jump on those quickly. You want your financing fully approved before closing day. Most lenders provide a closing disclosure (CD) at least 3 days before closing – review it carefully. It outlines all the costs, your final loan terms, and how much money you need to bring to closing.",
      "Final Walk-Through: Usually the day before or morning of closing, buyers do a final walk-through of the property to ensure it's in the same condition (or as agreed) and any negotiated repairs were completed. You'll coordinate this directly with the seller or their agent. It's often quick, 30 minutes or so, just checking that there's no new damage and that the place is empty (aside from any items that convey). If you find something egregious – like the seller removed appliances that were supposed to stay, or a new leak has sprung – you need to bring it up before closing. You could delay closing or require money held in escrow until it's resolved. In most cases, final walk-through is smooth. Bring along your contract to verify what stays (appliances, fixtures, etc.). If you used FirstLook for tours, you might ask if a FirstLook agent can accompany you on the walk-through for a second pair of eyes – they might do that as a courtesy or small fee.",
      "Close the Deal – Signing Day: Closing day will typically take place at the title company's office or a mutually agreed location. You (and anyone else on the loan/title, like a spouse) will need to bring a government ID and either a cashier's check or proof of wire transfer for the amount you owe (down payment + closing costs minus any deposit already paid). The title company will have a big stack of documents for you to sign – mortgage note, deed of trust, affidavits, title insurance forms, tax forms, etc. Without an agent present, you might feel a bit alone at that table, but know that it's routine. The title officer or attorney will walk you through each document's purpose. Take your time and read anything if you want; don't be afraid to ask \"what is this one for?\" – they'll explain. One thing you don't have to worry about is the seller trying any shenanigans at closing; by this point everything is agreed in writing, so it's mostly a formality of executing documents.",
      "Exchange of Keys and Celebration: After all papers are signed and money is transferred, you'll get the keys to your new home! If the seller is there (often sellers pre-sign ahead of time and might not be present), you might do a quick key handoff and friendly wave. Sometimes the seller's agent will hand you the keys – even though they weren't your agent, they often attend to wrap up their side. It can feel a bit odd not having a dedicated person to high-five at that moment, but trust me, your sense of accomplishment will fill that void. You did it largely on your own, and that's huge. Now the home is officially yours.",
      "Post-Closing Items: After closing, there are a few loose ends to tie. The title company will record the deed with the jurisdiction (you don't need to do anything). You should get copies of all the signed documents – usually a big packet or PDF. Keep those in a safe place; they include your deed and mortgage agreement. If you negotiated any home warranty or seller-paid item that extends post-closing, make sure to follow up on those. Also, ensure utilities are transferred to your name around the closing date, and change your address at the post office. If you didn't do it yet, update your insurance to homeowner's insurance effective on closing day (your lender likely required proof of insurance for closing anyway). And of course, plan your move!",
      "FirstLook's Closing Support: During the closing phase, FirstLook continues to act as your virtual guide. They'll coordinate with the title company to make sure everything is on track. For example, FirstLook might help by sending the title company all the contact info and documents as soon as you're under contract – essentially acting as a transaction coordinator. They can also schedule your closing appointment for you if needed. If any issues arise (like a title hiccup or a last-minute question about the settlement statement), FirstLook is just a call or text away to assist or explain. They can liaise with the seller or listing agent to smooth out any wrinkles. Basically, FirstLook remains your behind-the-scenes advocate up through closing. And beyond that, many FirstLook users note that the team follows up after closing to ensure you're settling in okay and to answer any new homeowner questions. By not paying a standard buyer's agent commission, you potentially saved thousands. That might mean extra cash for furniture, renovations, or just a bigger cushion in your bank account. Well done!"
    ]
  }
};
