
import { ClipboardCheck } from "lucide-react";

export const dueDiligenceSection = {
  id: "due-diligence",
  title: "Due Diligence and Inspections",
  icon: ClipboardCheck,
  content: {
    overview: "Once you have an accepted offer, the real work begins behind the scenes. This phase – often called due diligence or the inspection period – is where you ensure the home is in good condition and that you're fully comfortable with proceeding. Normally, a buyer's agent would help coordinate inspections, negotiate repairs, and keep track of deadlines. Without an agent, you'll need to be proactive in these areas, but it's entirely manageable with a bit of organization.",
    keyPoints: [
      "Hire a licensed home inspector and attend the inspection",
      "Review all seller disclosures and HOA documents carefully",
      "Understand appraisal process and other contingencies",
      "Track all deadlines to protect your contingency rights"
    ],
    content: [
      "Hire a Home Inspector: A thorough home inspection is a must, especially if you're buying without an agent's experienced eye on the property. As soon as your offer is accepted (often you'll have a set number of days in the contract to complete inspections – commonly 5-10 business days), hire a licensed home inspector to go through the house top to bottom. You can find a reputable inspector by reading online reviews, asking friends for recommendations, or using FirstLook's network of vetted inspectors. The cost is typically around $300-$600 depending on the size of the home – worth every penny for peace of mind. Plan to attend the inspection if you can. It's like a crash course in your future home: the inspector will point out issues (big and small), maintenance tips, and more. Take notes and ask questions. If the inspector flags any major issues (e.g., roof leaks, old electrical wiring, foundation cracks), you may need to get a specialist to evaluate or give estimates.",
      "Review Seller Disclosures and Documents: In parallel with the inspection, you should receive any disclosure documents from the seller. These can include things like a disclosure of known problems, past repairs, termite reports, or if it's a condo/HOA, a package of HOA documents and bylaws. Read these carefully! Without an agent to summarize them, you'll need to digest the info yourself. Look for red flags like mention of previous flooding, foundation repairs, or big upcoming HOA fee increases. If something is confusing (easy to happen, especially with HOA documents), consider consulting an attorney for clarity or asking the seller's agent directly for explanation. FirstLook can assist by highlighting key sections of these documents or suggesting questions to ask. Don't be shy about requesting clarification – you have a right to know what you're buying.",
      "Appraisal and Other Contingencies: If you're using a mortgage, the lender will schedule an appraisal to verify the home's value. This isn't something you do; it happens in the background. But you should know it's happening. Occasionally, the appraisal might come in lower than your purchase price – at which point you'd have to negotiate with the seller or bring extra cash. Many contracts have an appraisal contingency, allowing you to back out or renegotiate if that occurs. If you waived it, then you'd have to cover any shortfall. Since you likely don't have an agent advising you on such contingencies, hopefully you included an appraisal contingency (or at least knew the risk). Apart from appraisal, think of any other checks you want: for example, a radon test (common in some areas), a sewer line scope, or checking for lead paint in older homes. You can hire specialists for these if your general inspector doesn't cover them. It's up to you to decide what's needed based on the home's age and condition.",
      "Negotiate Repairs or Credits (if needed): Once inspections are done, you might find some issues that you feel the seller should address. Common examples: a leaking water heater, a termite infestation, or an HVAC system at end-of-life. Without a buyer's agent, you will directly communicate with the seller (or usually the seller's agent) to request repairs or a price reduction/credit. Keep your requests reasonable and focused on the big-ticket safety or functionality items – not cosmetic issues. For instance, asking to fix a structural problem is fair; asking for a $200 paint credit for scuffed walls might not go over well. Write up a clear list of what you want and why. FirstLook can provide a template for a repair request addendum and even advise on what's customary to ask for. Remember, the seller's agent knows you're unrepresented and might try to influence you, but remain firm on items that truly matter. If negotiating repairs feels daunting, this could be a good time to consult a real estate attorney or hire an on-demand agent for a flat fee to help craft the request – you'll still save money versus a full commission, and you'll have backup.",
      "Track Your Deadlines: In a typical contract, there are deadlines for inspection, appraisal, financing approval, etc. Without an agent's transaction coordinator reminding you, it's your responsibility to calendar these. If your inspection contingency expires on, say, the 10th day and you haven't formally requested repairs or given notice to cancel, you could lose that leverage. So mark the dates and act in advance. It helps to have all your key dates in one place (use your phone calendar with alerts, for example).",
      "FirstLook's Guidance During Due Diligence: FirstLook won't leave you hanging once you're under contract. The platform or your assigned support rep (if you opt for offer/closing assistance) will send you reminders of critical deadlines – \"Inspection contingency expires in 3 days, have you completed inspections?\" – that sort of nudge can be invaluable. They also maintain a roster of qualified home inspectors and specialists. Many FirstLook users tap into this network, essentially replacing the agent's referral role. Moreover, FirstLook can connect you with a real estate attorney at this stage if you don't already have one. Attorneys can be especially helpful in reviewing legal documents or drafting repair requests. In DC, having an attorney isn't required to buy a home, but it can be comforting to know you have a legal expert to call if anything gets complicated. FirstLook's goal here is to ensure you don't miss anything that a professional pair of eyes would catch – helping you be thorough and protected, without paying a percentage-of-sale commission for the privilege."
    ]
  }
};
