
import { DollarSign } from "lucide-react";

export const financingSection = {
  id: "financing",
  title: "Securing Financing",
  icon: DollarSign,
  content: {
    overview: "Financing is a crucial piece of the puzzle – and one where you'll want your ducks in a row early. Traditionally, a realtor would often insist you get pre-approved for a mortgage before they start showing you too many houses. This is wise advice, and it applies whether or not you have an agent. In a competitive market, having a mortgage pre-approval letter ready to go is almost mandatory when making an offer.",
    keyPoints: [
      "Shop around with multiple lenders to find the best rates and terms",
      "Get pre-approved before making offers to show sellers you're serious",
      "Understand different loan programs that fit your situation",
      "Stay within your comfort zone, not just your maximum approval amount"
    ],
    content: [
      "Shop for a Mortgage Lender: Start by researching and comparing a few lenders – these can be banks, credit unions, or online mortgage companies. You want a lender that offers competitive rates and good service (responsiveness is key when you're trying to close a deal fast). You can begin with your own bank to see what they offer, but don't stop there. Use online rate comparison tools or reach out to lenders that frequently work with first-time buyers. Many buyers without agents still manage to get quotes from multiple lenders – a smart move that could save you thousands in interest. Remember, you are not obligated to go with the first lender who pre-approves you; you're shopping around for the best deal.",
      "Get Pre-Approved: A pre-approval means a lender has checked your credit, income, and basic finances and is willing to lend you up to a certain amount (pending the home appraisal and other verification later). This comes in the form of a letter. To get one, you'll need to submit an application (often you can do this online in 15-20 minutes) and provide documents like pay stubs, W-2s, bank statements, etc. Within a day or two (sometimes even a few hours), the lender can issue a pre-approval letter stating you are pre-approved for up to $X amount. Get the pre-approval before you start making offers – sellers and their agents will take you far more seriously if you can say \"I'm pre-approved for my financing\" right off the bat. And don't worry, getting pre-approved doesn't lock you into that lender or loan; you can still negotiate or switch lenders later if needed.",
      "Know Your Loan Programs: When talking to lenders, inquire about what loan programs fit your situation. For example, if you have excellent credit and a 20% down payment, a conventional loan is likely best. If you have a smaller down payment, maybe an FHA loan could work (common for first-time buyers, requiring as little as 3.5% down). If you're a veteran or active military, VA loans offer zero down. DC and many states also have first-time buyer programs that a knowledgeable lender can help you access (like down payment assistance or special interest rates). Without an agent's guidance, you'll rely on the lender to walk you through these options – don't hesitate to ask questions. Good lenders are used to working directly with buyers and will happily explain the pros/cons of each loan type.",
      "Consider Your Budget vs. Approval: Just because you get pre-approved for, say, $600,000 doesn't mean you should spend that much. Revisit your own budget (from Step 1) and make sure the monthly payment at that price won't cramp your lifestyle. It's easy to get carried away when a bank green-lights a high amount, but you don't want to be \"house poor.\" One advantage of flying solo: there's no agent trying to push you to your max just to increase their commission. Stick to what you are comfortable with. You can tell your lender a lower number to put on the pre-approval letter if you prefer your offers to be for less (e.g., you might be approved up to $600k, but looking to buy around $500k – you can request the letter say $500k to not tip your hand on higher affordability).",
      "Prepare for Earnest Money and Down Payment: Part of financing prep is ensuring you have liquid funds ready for the earnest money deposit and down payment. When you make an offer, you'll typically need 1-3% of the price as a good-faith deposit (which later counts toward your down payment). Make sure that money is accessible (in a checking account, not tied up in long-term investments that take time to withdraw). Also avoid making any big changes that could upset your finances: don't open new credit lines, don't make large unexplained deposits, and don't switch jobs right before or during the home purchase process. Lenders will re-verify your info before closing, and any of those could jeopardize your loan approval.",
      "FirstLook's Role in Financing: While FirstLook isn't a lender, they do provide guidance to keep you on track. The platform will remind you to get pre-approved early, and can even connect you with partner lenders who are familiar with assisting buyers without traditional agents. These lenders know you might need a bit more direct communication (since there's no agent acting as a go-between) and they're prepared to give you that concierge service. FirstLook might also offer tools like a mortgage calculator or a checklist of documents you'll need for pre-approval, streamlining the process for you. In essence, FirstLook ensures that when you find \"the one\" – that perfect house – you're financially ready to pounce, with financing in place and no delays."
    ]
  }
};
