
import { FileText } from "lucide-react";

export const makingOffersSection = {
  id: "making-offers",
  title: "Making Offers and Negotiating",
  icon: FileText,
  content: {
    overview: "Here's the big moment – you've found the house and are ready to make an offer. Writing an offer and negotiating the price/terms is one of the most critical parts of a real estate deal. It's also the phase where not having an agent can feel most intimidating to many buyers. But take heart: with preparation, and possibly some targeted professional help, you can absolutely do this.",
    keyPoints: [
      "Research comparable sales to determine fair value",
      "Highlight the commission savings in your offer",
      "Use professional offer templates or services",
      "Stay flexible but know your limits"
    ],
    content: [
      "Crafting Your Offer (Offer Writing 101): A real estate offer in DC (and generally) is a legal contract, often called a Purchase and Sale Agreement or Contract of Sale. If you were working with an agent, they'd fill in a standard form for you. Going solo, you have a few ways to get the contract drawn up: you can obtain a standard contract form for your area (some state Realtor associations sell them online or you might find templates), work with a real estate attorney to draft one, or even ask the seller's agent to write the offer and send it to you to sign (though be cautious – the seller's agent represents the seller's interests, so have a lawyer review anything they draft on your behalf). Many solo buyers choose to hire an attorney at this stage for a flat fee to ensure the paperwork is done right. In fact, some attorneys specialize in \"transactional assistance\" for buyers without agents, charging a reasonable fee (often a few thousand dollars or less) to handle the contract and negotiation details – a fraction of the typical agent commission.",
      "Purchase Price: The amount you're offering for the home. This is obviously the headline term. Deciding on this number requires looking at recent comparable sales (comps) and the home's condition. Without an agent's CMA (comparative market analysis), you can research comps on Zillow or Redfin (they often show last sold prices of nearby homes) or ask your FirstLook tour agent for their opinion. Also consider how long the home has been on the market – if it's brand new to market in a hot area, you may need to offer at or above asking to be competitive. If it's been sitting for a while or needs work, you might go under asking. FirstLook can provide guidance here by supplying market data or even a suggested offer range if you ask. Remember, you might also factor in the commission savings: since you have no buyer's agent, in some cases you could justify an offer a bit lower because the seller isn't paying a buyer-agent commission. For example, one strategy is to offer ~3% below the list price, noting that it saves the seller the same amount in commissions – this way both you and the seller benefit from the cut of the middleman. (E.g., on a $250,000 listing, offering $242,500 could net the seller roughly the same as $250k would have with a buyer agent commission – a win-win.) Just be sure to communicate that rationale in a cover letter or email so the seller understands your logic.",
      "Earnest Money Deposit (EMD): The amount of a good-faith deposit you'll put down once the offer is accepted. Commonly 1–3% of the purchase price. This money goes into an escrow account (usually held by the title company) and later counts toward your down payment. If you walk away without a valid contingency reason, the seller may keep this, but if the deal closes it's yours. A larger EMD can signal a strong offer, but only put up what you're comfortable potentially forfeiting (in worst case). You'll typically need to write a check or send a wire within a few days of acceptance.",
      "Financing and Inspection Contingencies: These clauses give you windows to secure your mortgage approval and inspect the home. A financing contingency allows you to exit if you fail to get approved, while an inspection contingency lets you request repairs or cancel if serious issues are found. Many buyers keep these contingencies, though in ultra-competitive situations some waive them (risky unless you're very sure). Without an agent, lean conservative – these are your safety nets. You can also state an inspection as \"inspection with right to terminate\" – basically, you won't ask for repairs but reserve the right to walk away if the inspection is unsatisfactory.",
      "Closing Date and Other Terms: Propose a date for settlement (closing). Typically 30 to 45 days from contract acceptance for financed purchases. Try to be flexible to the seller's needs here – if they want a quick close or need more time, accommodating that can make your offer more attractive. FirstLook can find out from the listing agent if there's a preferred closing timeframe. You can also offer a rent-back if the seller needs to stay in the home for a short period after closing. Keep your offer as clean and simple as possible. Too many demands can turn off a seller. Focus on the key deal points – price, contingencies, timing – and don't clutter with minor asks.",
      "Negotiation Strategies: Once you submit your offer, the seller can accept, reject, or counter-offer. Without a buyer's agent, you'll be dealing directly with the seller or their agent. Leverage your position as an unrepresented buyer by highlighting the commission savings – both parties can benefit when there's no buyer's agent commission. Keep communication professional and prompt; since you don't have to play telephone tag through two agents, you can respond quickly. Focus on win-win solutions rather than fault-finding, and avoid disparaging the home as a negotiation tactic. Have a limit and plan B ready, and don't hesitate to bring in professional help for negotiation advice if needed.",
      "FirstLook can provide standard contract forms or templates for DC area transactions. In many cases, FirstLook has an arrangement where a licensed agent (affiliated with their service) or an attorney will help draft the offer paperwork for you when you're ready, ensuring everything is filled out correctly and legally compliant. This might come as a one-time flat fee or as part of a premium package, but remember – even paying a few hundred dollars for professional offer drafting is a far cry from paying a 3% commission on the whole home price. During negotiations, FirstLook acts as your on-demand transaction coordinator, helping you understand counter-offers, providing market data, and connecting you with experts when needed."
    ]
  }
};
