
import { Home } from "lucide-react";

export const movingInSection = {
  id: "moving-in",
  title: "Moving In and Next Steps",
  icon: Home,
  content: {
    overview: "Time to enjoy the fruits of your labor – you're a homeowner now, and moving day is here! While moving in might seem straightforward compared to the homebuying gauntlet you just went through, there are still some tips to ensure a smooth transition. And as you settle in, it's worth reflecting on how FirstLook has helped you reach this point and what lies ahead as a confident, commission-savvy homeowner.",
    keyPoints: [
      "Plan your move well in advance with proper organization",
      "Use your commission savings wisely for improvements or savings",
      "Handle post-closing items promptly and stay organized",
      "Enjoy your achievement and new home ownership journey"
    ],
    content: [
      "Plan Your Move Early: As soon as you know your closing date, start organizing the move. Book movers or a truck, start packing gradually, and line up any help you might need. Without an agent, you may not have gotten a glossy \"new home\" packet with checklists – but plenty of moving checklists exist online. Key tasks include: transferring utilities (electric, water, gas, internet) to your name effective your closing day, scheduling any immediate work you want done in the new home (painting, deep cleaning) before you bring all your stuff in, and updating your address for banks, employer, subscriptions, etc. If you're renting your current place, schedule the end of lease and any cleaning to get your deposit back. FirstLook might provide a handy moving day checklist as part of their service, covering often-forgotten items like updating your voter registration and driver's license address.",
      "Use Your Savings to Your Advantage: One amazing thing about buying without a traditional agent is the money you've saved. Earlier, we talked about possibly saving around 3% of the purchase price by avoiding a buyer agent commission. On a $500,000 home, that could be roughly $15,000 (minus any flat fees you paid to FirstLook or attorneys, which are relatively small). Think about that – $15k could cover a lot of improvements or several months of mortgage payments. Consider earmarking some of those savings towards making your new house a home. Maybe you'll build that home theater, invest in energy-efficient appliances, or simply bolster your emergency fund (always a wise move as a new homeowner). The point is, you get to decide, rather than having it invisibly disappear as an agent commission. It's a tangible reward for taking the initiative to go solo.",
      "Tie Up Any Loose Ends: After moving in, there might be a few lingering items from the transaction. Perhaps the seller agreed to mail you an extra set of keys or you're waiting on a contractor's invoice that was a condition of closing. Stay on top of these until they're resolved. If you discover an issue in the house that was supposed to be fixed and wasn't, you can sometimes address it even post-closing if it was explicitly agreed upon. Check your contract and don't hesitate to reach out to the seller (politely) if needed. Without agents, communication is direct, which can actually resolve things faster in some cases. If something serious emerges that wasn't disclosed, consult your attorney – but hopefully, with thorough due diligence, there are no surprises.",
      "Enjoy Homeownership (and Know You Did It Differently): Now comes the fun part – making the place your own! Paint those walls, plant that garden, throw that housewarming party (you earned it). Homeownership is a journey, and you'll keep learning as you go – maintenance tips, how to deal with property taxes, maybe joining the neighborhood association. One thing you've proven by buying without a realtor is that you're a proactive, informed consumer. That will serve you well going forward. You won't hesitate to seek out information and make decisions confidently about your home. And if/when the time comes to sell or buy again, you'll be in a great position to weigh your options – you might even use FirstLook (or similar) on the sell side, or negotiate even harder knowing what you know now.",
      "Stay Connected with FirstLook: Just because the transaction is over doesn't mean your relationship with FirstLook has to end. Many users stay in touch – whether it's getting recommendations for reliable contractors or even using FirstLook's resources for homeowner education (some platforms offer workshops on home maintenance or refinancing tips, for example). And of course, if you have friends or family looking to buy a home in a modern way, you can share your experience. There's often referral benefits too – another bonus of being part of the FirstLook community.",
      "Finally, take a moment to pat yourself on the back. You navigated the entire homebuying process without a traditional realtor, avoiding the limitations and costs of the old model. You proved that with the right approach and support, buyers have more power and savvy than ever. The real estate industry is changing: flat-fee and à la carte services are rising, and consumers are pushing back on high commissions. You're at the forefront of that change. We hope this step-by-step guide has been clear, empowering, and useful in showing that buying a home without an agent is not only feasible – it can be downright liberating. Welcome to your new home, purchased your way. Here's to a future where homebuyers like you have FirstLooked their way to success – enjoying the home they want, the control they need, and the savings they deserve. Cheers!"
    ]
  }
};
