
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uugchegukcccuqpcsqhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Z2NoZWd1a2NjY3VxcGNzcWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTU4NzQsImV4cCI6MjA2NDI5MTg3NH0.4r_GivJvzSZGgFizHGKoGdGnxa7hbZJr2FhgnAUeGdE";

// Optimized Supabase client with enhanced real-time configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 0.5, // Further reduced to prevent rate limiting
    },
    heartbeatIntervalMs: 60000, // Increased to 60s to reduce connection overhead
    reconnectAfterMs: (tries: number) => {
      // Exponential backoff with jitter and longer delays
      const baseDelay = Math.min(tries * 3000, 60000);
      const jitter = Math.random() * 2000;
      return baseDelay + jitter;
    },
    timeout: 30000, // 30 second timeout
  },
  global: {
    headers: {
      'X-Client-Info': 'firstlook-web-app-unified',
    },
  },
});
